
GO
SET IDENTITY_INSERT [dbo].[Squad] ON 

INSERT [dbo].[Squad] ([SquadId], [Name], [IsLeader], [EmployeeId]) VALUES (2, N'NAD', 1, 11)
INSERT [dbo].[Squad] ([SquadId], [Name], [IsLeader], [EmployeeId]) VALUES (3, N'ROCKET', 1, 25)
INSERT [dbo].[Squad] ([SquadId], [Name], [IsLeader], [EmployeeId]) VALUES (4, N'SENTRY', 1, 27)
INSERT [dbo].[Squad] ([SquadId], [Name], [IsLeader], [EmployeeId]) VALUES (5, N'BRAVO', 1, 22)
INSERT [dbo].[Squad] ([SquadId], [Name], [IsLeader], [EmployeeId]) VALUES (6, N'BRASIL', 1, 12)
INSERT [dbo].[Squad] ([SquadId], [Name], [IsLeader], [EmployeeId]) VALUES (7, N'MANAGEMENT', 1, 1)
INSERT [dbo].[Squad] ([SquadId], [Name], [IsLeader], [EmployeeId]) VALUES (8, N'AANS', 1, 5)
INSERT [dbo].[Squad] ([SquadId], [Name], [IsLeader], [EmployeeId]) VALUES (9, N'APS.net', 1, 17)
INSERT [dbo].[Squad] ([SquadId], [Name], [IsLeader], [EmployeeId]) VALUES (10, N'APS', 1, 1)
INSERT [dbo].[Squad] ([SquadId], [Name], [IsLeader], [EmployeeId]) VALUES (11, N'Work Item Tracking', 1, 5)
INSERT [dbo].[Squad] ([SquadId], [Name], [IsLeader], [EmployeeId]) VALUES (12, N'NAD', 0, 8)
INSERT [dbo].[Squad] ([SquadId], [Name], [IsLeader], [EmployeeId]) VALUES (13, N'NAD', 0, 9)
INSERT [dbo].[Squad] ([SquadId], [Name], [IsLeader], [EmployeeId]) VALUES (14, N'NAD', 0, 18)
INSERT [dbo].[Squad] ([SquadId], [Name], [IsLeader], [EmployeeId]) VALUES (15, N'NAD', 0, 34)
INSERT [dbo].[Squad] ([SquadId], [Name], [IsLeader], [EmployeeId]) VALUES (16, N'NAD', 0, 37)
INSERT [dbo].[Squad] ([SquadId], [Name], [IsLeader], [EmployeeId]) VALUES (17, N'NAD', 0, 40)
INSERT [dbo].[Squad] ([SquadId], [Name], [IsLeader], [EmployeeId]) VALUES (18, N'ROCKET', 0, 14)
INSERT [dbo].[Squad] ([SquadId], [Name], [IsLeader], [EmployeeId]) VALUES (19, N'ROCKET', 0, 13)
INSERT [dbo].[Squad] ([SquadId], [Name], [IsLeader], [EmployeeId]) VALUES (20, N'ROCKET', 0, 15)
INSERT [dbo].[Squad] ([SquadId], [Name], [IsLeader], [EmployeeId]) VALUES (21, N'ROCKET', 0, 30)
INSERT [dbo].[Squad] ([SquadId], [Name], [IsLeader], [EmployeeId]) VALUES (22, N'SENTRY', 0, 29)
INSERT [dbo].[Squad] ([SquadId], [Name], [IsLeader], [EmployeeId]) VALUES (23, N'SENTRY', 0, 28)
INSERT [dbo].[Squad] ([SquadId], [Name], [IsLeader], [EmployeeId]) VALUES (24, N'BRAVO', 0, 24)
INSERT [dbo].[Squad] ([SquadId], [Name], [IsLeader], [EmployeeId]) VALUES (25, N'BRAVO', 0, 23)
INSERT [dbo].[Squad] ([SquadId], [Name], [IsLeader], [EmployeeId]) VALUES (26, N'BRAVO', 0, 3)
INSERT [dbo].[Squad] ([SquadId], [Name], [IsLeader], [EmployeeId]) VALUES (27, N'BRAVO', 0, 21)
INSERT [dbo].[Squad] ([SquadId], [Name], [IsLeader], [EmployeeId]) VALUES (28, N'BRAVO', 0, 5)
INSERT [dbo].[Squad] ([SquadId], [Name], [IsLeader], [EmployeeId]) VALUES (29, N'BRASIL', 0, 24)
INSERT [dbo].[Squad] ([SquadId], [Name], [IsLeader], [EmployeeId]) VALUES (30, N'BRASIL', 0, 41)
INSERT [dbo].[Squad] ([SquadId], [Name], [IsLeader], [EmployeeId]) VALUES (31, N'BRASIL', 0, 16)
INSERT [dbo].[Squad] ([SquadId], [Name], [IsLeader], [EmployeeId]) VALUES (32, N'AANS', 0, 6)
INSERT [dbo].[Squad] ([SquadId], [Name], [IsLeader], [EmployeeId]) VALUES (33, N'AANS', 0, 22)
INSERT [dbo].[Squad] ([SquadId], [Name], [IsLeader], [EmployeeId]) VALUES (34, N'AANS', 0, 37)
INSERT [dbo].[Squad] ([SquadId], [Name], [IsLeader], [EmployeeId]) VALUES (35, N'AANS', 0, 10)
INSERT [dbo].[Squad] ([SquadId], [Name], [IsLeader], [EmployeeId]) VALUES (36, N'AANS', 0, 39)
INSERT [dbo].[Squad] ([SquadId], [Name], [IsLeader], [EmployeeId]) VALUES (37, N'AANS', 0, 21)
INSERT [dbo].[Squad] ([SquadId], [Name], [IsLeader], [EmployeeId]) VALUES (38, N'APS.net', 0, 18)
INSERT [dbo].[Squad] ([SquadId], [Name], [IsLeader], [EmployeeId]) VALUES (39, N'APS.net', 0, 19)
INSERT [dbo].[Squad] ([SquadId], [Name], [IsLeader], [EmployeeId]) VALUES (40, N'APS.net', 0, 38)
INSERT [dbo].[Squad] ([SquadId], [Name], [IsLeader], [EmployeeId]) VALUES (41, N'Work Item Tracking', 0, 39)
INSERT [dbo].[Squad] ([SquadId], [Name], [IsLeader], [EmployeeId]) VALUES (42, N'Work Item Tracking', 0, 32)
INSERT [dbo].[Squad] ([SquadId], [Name], [IsLeader], [EmployeeId]) VALUES (43, N'Work Item Tracking', 0, 33)
INSERT [dbo].[Squad] ([SquadId], [Name], [IsLeader], [EmployeeId]) VALUES (44, N'Work Item Tracking', 0, 20)
SET IDENTITY_INSERT [dbo].[Squad] OFF
GO
